### ISSUE TITLE
Issuies with Super chart on App

### ISSUE THREAD

**Issue by OleksandrGora** [blynkkk/beta#174] opened 2021-07-08 11:51 UTC
Everything concerns App version.
When you launch the app, Superchart always stars showing Live data (unlike the previous version of the app which remembered your period choice. In my opinion, it was better).
After launching the app (when Live data is chosen by default) if you roll up Superchart on full screen you can see only Live data. Changing period does not help, always "No data yet" (or "No data") is shown.
When you firstly chose a period, then set full screen mode, then you firstly see again "No data yet" (bug as well), but now changing of the period helps. You can see stored data.

**Comment by doom369** [comment] 2021-07-08 11:59
@OleksandrGora hello. Android/ios?

**Comment by OleksandrGora** [comment] 2021-07-08 12:01
Android.

**Comment by alexkipar** [comment] 2021-07-08 13:26
@OleksandrGora is it Blynk IoT app, latest version?

**Comment by OleksandrGora** [comment] 2021-07-08 13:37
Yes, it is.

**Comment by alexkipar** [comment] 2021-07-08 14:44
@OleksandrGora yep, we do not persist the period selection across app's launches, but it should be persisted in runtime. I will check the issue with fullscreen not working selection. On the persisting selection across app launch and full close - we will probably implement it later.

**Comment by thorathome** [comment] 2021-07-09 00:41
Another SuperChart issue...
I have multiple Devices on the same Template. When I create multiple Tiles for these Devices, I usually put in a SuperChart. However, these SuperCharts in different Tiles ALL duplicate the same chart title and other behaviors. This is unexpected.  

For example: I have multiple temperature sensors on the same 'Temperature Sensor' Template. They all measure different things, have different temperature ranges. However, the SuperChart Titles and other characteristics, even at the Datastream level, get copied to all of the other Tiles based on the same Template. 

So I cannot have a SuperChart Title of "Outside Temperature" because all the other SuperCharts based on the same Temperature Sensor Template now have the title of Outside Temperature. This copying across multiple SuperCharts in different Tiles extends to the Datastreams, too.

Is this behavior intended? Thanks.

**Comment by alexkipar** [comment] 2021-07-09 09:39
@thorathome 

The template dashboard setup is same for all the devices within this template, it is the intended behavior. If you have several different devices with some differences in their data or logic - you need to create a separate template for each different device.

**Comment by thorathome** [comment] 2021-07-09 13:59
Very helpful and clear response. Thanks.  

To move a device from one template to a new template, I had to delete the device, then create a new device linked to the new template. Is there a smoother way to move a device from one template to another? 
Thanks again.

**Comment by alexkipar** [comment] 2021-07-09 14:05
@thorathome, unfortunately, there is no other way currently.

**Comment by blynkkk** [comment] 2021-07-09 14:15
Do we understand correctly that you have multiple identical sensors (devices), but due to a different use-cases, charts should be renamed by the end-user.

For example: i have 2 of your sensors.
1. Is set up as indoor and chart should be name Indoor Temp
2. Is set up as outdoor and chart should be named Outdoor Temp

However, both of the sensors operate on the same firmware. 

Is that correct?

**Comment by thorathome** [comment] 2021-07-09 19:54
I'm thinking that the Admin would set up the Tiles to reflect the use cases for the end-users. 

Your use case is correct. One Tile has a SuperChart called Indoor Temperature. The other should be called Outdoor Temperature. I would expect an Admin to set this up. Two tiles, two devices, one template. 

It may get more interesting when the two temperature sensors have vastly different ranges. In my case, one sensor measures Outdoor temperature between 10 degrees F and 110 degrees F (-12-42 deg. C). The other identical sensor measures temperature in a hot tub with temperatures between 100 and 105 degrees F (38-41 deg C). I want the Outdoor temperature SuperChart to show temperatures in that large range, can perhaps use the Auto scaling option. For the hot tub, I want a fixed and more narrow Y-axis scale between 100 and 105 degrees F. 

I notice the Labeled Values widgets do not appear to inherit titles or colors from other tiles using the same template. I understand why you chose to have the SuperChart options behave the way they do under the same template. It does seem to limit the flexibility of the templates, though. 

I hope this is helpful.

**Comment by OleksandrGora** [comment] 2021-07-14 14:47
@alexkipar, this bug has been eliminated:
> When you firstly chose a period, then set full screen mode, then you firstly see again "No data yet" (bug as well).
Thanks.

But this one has not:
> After launching the app (when Live data is chosen by default) if you roll up Superchart on full screen you can see only Live data. Changing period does not help, always "No data yet" (or "No data") is shown.

**Comment by alexkipar** [comment] 2021-07-14 14:48
@OleksandrGora can you send logs once more

**Comment by OleksandrGora** [comment] 2021-07-14 14:52
Are there logs in the App?

**Comment by OleksandrGora** [comment] 2021-07-14 15:16
https://user-images.githubusercontent.com/85741797/125646631-0bf3ec8b-df09-4252-a9b3-f9ae868fd8f4.mp4

Launching the app is shown on video. It has not been shown a moment when you change the period before setting full screen mode. But be sure: everything works properly then.

**Comment by alexkipar** [comment] 2021-07-14 17:40
> Are there logs in the App?

on the about screen there is an option to send logs, click on it and select gmail app - file with the logs will be attached to the email, as well as recipient email.

**Comment by OleksandrGora** [comment] 2021-07-15 07:23
@alexkipar Sent.

**Comment by alexkipar** [comment] 2021-07-15 10:28
@OleksandrGora thanks, seems it is too small. Can you reproduce this issue and send the log again later?

**Comment by OleksandrGora** [comment] 2021-07-15 10:47
@alexkipar Reproduced. Sent.

**Comment by alexkipar** [comment] 2021-07-15 11:28
@OleksandrGora thanks, I see now the cause of the issue, looks like the next version will contain a fix to this issue.

**Comment by DmytroTool** [comment] 2021-07-16 14:14
@OleksandrGora Can you check with your device one more time, please, it seems to be fixed for now.

**Comment by alexkipar** [comment] 2021-07-16 14:17
@DmytroTool no, it will be fixed with the new build being available.

**Comment by alexkipar** [comment] 2021-07-18 10:56
@OleksandrGora please check 1.1.9 version which should be already available or will be available to update quite soon

**Comment by OleksandrGora** [comment] 2021-07-21 07:59
@alexkipar The issue is solved (except of remembering period choice across app's launches). You can close the issue from my side, but there was a suggestion from @thorathome.

**Comment by alexkipar** [comment] 2021-08-09 09:55
@OleksandrGora, the latest app's version should remember period choices, reopen if it is not working on your side.

**Closed as completed by alexkipar** 2021-08-09 09:55 UTC
Labels: enhancement, Android, ready to test
