### ISSUE TITLE
Units do not match datastream setting

### ISSUE THREAD

**Issue by Selah50** [blynkkk/beta#171] opened 2021-07-06 16:55 UTC
Issue 1: I have 2 datastreams that are set to Fahrenheit. Yesterday, they started displaying in Celsius.
Issue 2: The numeric input widget that is displaying Celsius and not Fahrenheit is accepting an input that is above/below the min/max settings for its datastream when using the + and - increment buttons.

Video: https://photos.app.goo.gl/LeZde31q3W1zgcYX8

This issue is on android
[samsung_SM_G975F_29_2021_07_06.log](https://github.com/blynkkk/blynk_Issues/files/6771553/samsung_SM_G975F_29_2021_07_06.log)

**Comment by doom369** [comment] 2021-07-06 17:04
> Issue 1: I have 2 datastreams that are set to Fahrenheit. Yesterday, they started displaying in Celsius.

Could you please clarify - do you mean they show converted values in the widget or they just show the wrong suffix?

>  Issue 2: The numeric input widget that is displaying Celsius and not Fahrenheit is accepting an input that is above/below the min/max settings for its datastream when using the + and - increment buttons.

@alexkipar Please take a look.

**Comment by alexkipar** [comment] 2021-07-06 17:07
@doom369 "unitSystem":"METRIC" in the profile.settings, and also datastreams returned by the server (in get device dashboard command) are using Celcius units

**Comment by Selah50** [comment] 2021-07-06 17:11
It appears that it is just displaying the wrong suffix.

**Comment by doom369** [comment] 2021-07-06 17:20
> "unitSystem":"METRIC" in the profile.settings

@alexkipar Why do we allow that in the app? It should be hidden until it's fully implemented. The default value should be null.

> are using Celcius units

Yes, because it's a metric system. Response is correct.

**Comment by alexkipar** [comment] 2021-07-06 17:22
@doom369 it is definitely disabled in settings, while the value is Metric

**Comment by doom369** [comment] 2021-07-06 17:23
@alexkipar that could be set only from the mobile...

**Comment by doom369** [comment] 2021-07-06 17:23
@alexkipar that could be set only from the mobile...

**Comment by alexkipar** [comment] 2021-07-06 17:24
@doom369 it can't be set from the app

**Comment by alexkipar** [comment] 2021-07-06 17:37
@Selah50 till the end of the week, we will have a small bugfix update; I suppose this issue will be fixed.

**Comment by mike1964Blynk** [comment] 2021-07-09 17:19
Same issue, Template set to "Fahrenheit",  Mobile Dashboard shows Celsius ("C"). will wait for the update.

Thanks, 
Mike

**Comment by doom369** [comment] 2021-07-09 18:00
@alexkipar have you released the update?

**Comment by alexkipar** [comment] 2021-07-09 18:18
Not yet, this issue will be fixed in next build it will be available on weekend

**Comment by doom369** [comment] 2021-07-13 15:39
@Selah50 @mike1964Blynk should be fixed with the latest app. Please reopen if not fixed.

**Closed as completed by doom369** 2021-07-13 15:39 UTC
Labels: bug, Android, ready to test, web, deployment required

**Comment by mike1964Blynk** [comment] 2021-07-13 15:44
Confirmed, Thank you, Sent from my Galaxy
-------- Original message --------From: Dmitriy Dumanskiy ***@***.***> Date: 7/13/21  11:40 AM  (GMT-05:00) To: blynkkk/blynk_Issues ***@***.***> Cc: mike1964Blynk ***@***.***>, Mention ***@***.***> Subject: Re: [blynkkk/blynk_Issues] Units do not match datastream setting (#171) 
@Selah50 @mike1964Blynk should be fixed with the latest app. Please reopen if not fixed.
