### ISSUE TITLE
Widget does not function unless app restarted

### ISSUE THREAD

**Issue by thomoray** [blynkkk/beta#7] opened 2021-03-27 08:55 UTC
Phone Sony XZ2 Android version 9 
Tablet Samsung S6 lite Android version 11

After adding a widget and going back to the device the widget does not make ESP8266 react. 
If I leave the app either closing or placing it into the background then after coming back in the app refreshes and the widget functions as expected.

Steps to reproduce.
Go to developer mode inside of the app.
Open the device and add a button widget.
Assign virtual pin as setup in the ESP8266 sketch/web dashboard.
Navigate back to the device out of developer mode.
Try turning on and off the virtual pin.

In my case, I have this on a relay and the relay does not react.
After exiting the app/reloading the relay responds.

**Comment by alexkipar** [comment] 2021-03-27 13:51
@thomoray does the device page is opened when you go into the developer mode?

**Comment by thomoray** [comment] 2021-03-28 03:59
Here is link for a recording of the steps I take to reproduce the issue hope it helps. 

https://drive.google.com/file/d/1-k76cyB0Csjh6Snix9sEszQYNIbV2SkP/view?usp=drivesdk

**Comment by alexkipar** [comment] 2021-03-28 04:43
@thomoray should be fixed with just published 1.0.6 - hope it will be available to update quite soon

**Comment by Peterkn2001** [comment] 2021-03-28 07:54
Seems to be fixed in version 1.0.6 of the app with the testing that I've done, but maybe allow @thomoray to confirm before closing?

Pete.

**Comment by doom369** [comment] 2021-03-28 09:08
Closing. @thomoray please reopen if reproduced with the latest build.

**Closed by doom369** 2021-03-28 09:08 UTC
Labels: Android, bug, ready to test
