### ISSUE TITLE
I cannot add device

### ISSUE THREAD

**Issue by italex33** [blynkkk/beta#113] opened 2021-06-08 06:44 UTC
I followed these instructions listed here: https://docs.blynk.io/en/mobile-applications/device-management/add-new-device, but it is impossible to find a device  the way is listed here. I have two Arduino MKR1010,  I cannot see any one of them in my WiFi settings, I am using the iPhone 12 Pro Max latest OS. Some clarification will be appreciated.

**Comment by vshymanskyy** [comment] 2021-06-08 13:14
@italex33 Did you flash both devices with the Blynk.Edgent?
Do you see both devices broadcasting a WiFi network? Try scanning WiFi networks from your PC.

**Comment by italex33** [comment] 2021-06-09 02:27
I am able to place the Particle Photon is listening mode(blinking blue), I see it in the iPhone Settings, also I see it in my computer WiFI list, but I cannot connect to it using the steps listed on the link I sent prior. 
The MKR1010 I have not idea how to place it in listening mode.   I tried to flash the MKR1010 using the Blynk.Edgent,  no joy. This is what I get:

Arduino_MKR1010:4:10: fatal error: BlynkEdgent.h: No such file or directory
 #include "BlynkEdgent.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
exit status 1
BlynkEdgent.h: No such file or directory

Library is installed, I checked  and rechecked it.

**Comment by blynkkk** [comment] 2021-06-09 15:55
Particle devices are not supported for wifi provisioning. Stick to Static Tokens for now

**Comment by italex33** [comment] 2021-06-09 21:34
How about  the MKR1010? I cannot add at all.

**Comment by doom369** [comment] 2021-06-10 03:40
> How about the MKR1010? 

It's supported.

> I cannot add at all.

@vshymanskyy please advise and add section to troubleshooting.

**Comment by vshymanskyy** [comment] 2021-06-10 04:54
Please provide more info - Device logs specificly.

**Comment by nasserbek** [comment] 2021-06-10 07:57
Dear Blynkers, 
I can't add my existance device ESP32 used with Blynk old version.

In the Blynk Platform device info I edited the Auth key and changed it to be the same as the one I was using before, then I copied the 2 lines for template and device defines and inserted them in the top of the main code.

After dwonloading Edgent_esp32 , I connect to the wifi SSID of the EXP32 but when I open Blynk Iot I don't see the menu and hence I cann't add the new device.

Is that because when I switch the mobile to connect to WIFI (no internet) the 4G is disabled and then can't connect to server?

Thanks

**Comment by doom369** [comment] 2021-06-10 08:44
> In the Blynk Platform device info I edited the Auth key

Why would you do that? Have you checked the getting started - https://docs.blynk.io/en/getting-started/activating-devices

**Comment by nasserbek** [comment] 2021-06-10 08:59
Thanks for your fast replay..
I followed that link, **Activating device with a Static Auth Token** .
Under prepare your sketch step 4, from Arduino IDE open **edgent_esp32**.
but Edgent_est32 dosen't contain the code shown with the 4 lines to be edited with my credential Auth, ssid, pw... I see instead the code of Edgent_exp32.ino, should I replace it with the shown code wit Blynk.run .?

regards

**Comment by doom369** [comment] 2021-06-10 09:04
> I followed that link, Activating device with a Static Auth Token .

But why did you edited the Auth Token? It was already there. You need to copy it to hardware, not change it.

> but Edgent_est32 dosen't contain the code shown with the 4 lines to be edited with my credential Auth, ssid, pw... I see instead the code of Edgent_exp32.ino, should I replace it with the shown code wit Blynk.run .?

@vshymanskyy please take a look, docs code example totally different from the library example.

**Comment by nasserbek** [comment] 2021-06-10 09:15
@doom369 : 
I edited the Auth Token because it was possibile to edit then I thought I could use my existing Auto Key for my old device to use it into the new device.. Whey it is possible to edit the auth key? what is the scope for editing the auth key?

**Comment by nasserbek** [comment] 2021-06-10 11:47
Well, I removed the device from the Platform and added a new one.
-Following the doc link option B "Static Token"
-Copied the simple code after replacing the 2 defines lines , new auth key for the new device and with my wifi credential.
-Downloaded the code into the esp32
-Still see the device offline on my mobile and on the Web...

On the serial monitor I see this message:
[20045] Connecting to blynk-cloud.com:80
[20886] Invalid auth token

What is missing?

Thanks

**Comment by italex33** [comment] 2021-06-10 12:25
This is what I have done so far, it seems to be working. I am using the Arduino MKR1010.  Add the two lines  like this: 

#define BLYNK_TEMPLATE_ID "TMPLxxx3OMI"
#define BLYNK_DEVICE_NAME "MKR1010"

Add this line: char auth[] = "6Hlg5o_oh_q9uL0vxxxxxxKntRQ_w";
Add this line: BlynkTimer timer;

In setup add:  Blynk.begin(auth, ssid, pass);

In loop void add:
Blynk.run();
timer.run();

Flash it to your device, and voila! It works! 

Very simple.  The example using BlynkEdgent is VERY complex! Besides that it looks like is just for the ESP32.  Too many tabs.
Finally, if you define a virtual pin, in MAX change it to some other value than 1,  I was not getting much until I change that value to 1000000000. 

We need a dark theme, please. 

UPDATE:
Same code loaded on a Particle Photon, and it works. 


#define BLYNK_TEMPLATE_ID "TMPLcxxxx3OMI"
#define BLYNK_DEVICE_NAME "MKR1010"
#include <blynk.h> // This #include statement was automatically added by the Particle IDE.

 char auth[] = "6Hlg5o_oh_qxxxxxxxk0m5KntRQ_w"; 
 char ssid[] = "Crypto 2.4Ghz";
 char pass[] = "vfrXXXXX";
 BlynkTimer timer;
 
void setup()
  {
  Blynk.begin(auth);
  timer.setInterval(1000, test);
  } 
 
void test()
{
int counter;
counter = millis() / 1000;
Blynk.virtualWrite(V0, counter);
}


void loop()
 {
 Blynk.run();
 timer.run(); 
 }

**Comment by doom369** [comment] 2021-06-10 12:35
> [20045] Connecting to blynk-cloud.com:80

That's wrong host, looks like you are using old firmware.

**Comment by nasserbek** [comment] 2021-06-10 13:09
@doom369 : 
Yes, it looks like the host was wrong, I didn't change anything but after trying several times it works and I can see the device online with the same code ..

[2044] Connecting to blynk.cloud:80
[2753] Ready (ping: 201ms).

Thanks

**Comment by nasserbek** [comment] 2021-06-10 13:58
On the web dashboard I added a label connected with the Device that changes every 6 secs, on the mobile it works and I see it changes but on the Web dashboard doesn't move to make work I must refresh the page .. it looks like the web dashboard can't do a continuous polling from the device ..

Editing the Auth key is also working, I'm using the Auth key used with old blynk with old server and it works with old blynk app, to make it work with the new blynk I need to change only the server keeping the same Auth key..
#define BLYNK_SERVER "blynk-cloud.com"
#define BLYNK_SERVER_IOT  "blynk.cloud"

Regards.

**Comment by doom369** [comment] 2021-06-10 14:01
> but on the Web dashboard doesn't move to make work I must refresh the page

Looks like a bug. We'll check. Thanks for the report. Also, it would be nice to create a separate ticket, rather than put everything in one.

**Comment by doom369** [comment] 2021-06-10 15:25
@nasserbek we were not able to reproduce. Do you have a datastream assigned to that widget? Do you open the correct device? Please double-check your settings.

**Comment by nasserbek** [comment] 2021-06-11 00:30
@doom369 
Yes of course I created a data stream with named "Sec" on the virtual Pin V11, in fact it works fine on my the mobile app, under the device web dash board but not working under Template dash board..

![dash board under device](https://user-images.githubusercontent.com/54413843/121613286-b96c9580-ca8e-11eb-9b28-739d443afc54.JPG)

![dash board under template](https://user-images.githubusercontent.com/54413843/121613300-bf627680-ca8e-11eb-890a-a9d2c05e6030.JPG)

In the second picture and under template I must refresh the page to see the real time value, also when I click on mobile dash board I don't see my mobile dashboard created in the app but on the app I see only what I create on the Web...

Regards

**Comment by doom369** [comment] 2021-06-11 04:20
@nasserbek it's a template dashboard (with a fake data), it's not a real device dashboard. It just shows you how your device dashboard (with real data) will look like.

> I click on mobile dash board I don't see my mobile dashboard created 

The Mobile dashboard created in the mobile app, not on the web.

**Closed as completed** 2021-06-15 17:57 UTC
