### ISSUE TITLE
Web Dashboard slider glitch

### ISSUE THREAD

**Issue by CMJ111** [blynkkk/beta#213] opened 2021-08-25 14:05 UTC
Web dashboard slider on Windows10, Chrome Browser

When slider is left at minimum range value a value of zero is sent. If the slider is moved above min val it works properly.

**Comment by doom369** [comment] 2021-08-25 14:08
> When slider is left at minimum range value a value of zero is sent.

Why is that a bug? What is your minimum setting for the datastream?

**Comment by CMJ111** [comment] 2021-08-25 14:24
Same as the minimum setting of slider(not zero) but  if that's the way its supposed to work then I misunderstood.

**Comment by CMJ111** [comment] 2021-08-25 14:28
To be specific DataStream range is set from 150 - 300.  Slider range is set to 150 - 300.  When slider is at 150 it sends a value of 0 when it is set to 151 or above it sends that value.  The slider isn't ranging anything so why would it ever send a zero if you do not have a minimum value of zero set?

**Comment by doom369** [comment] 2021-08-25 14:45
@CMJ111 looks like a bug. Thanks for the detailed info. We'll check.

**Comment by doom369** [comment] 2021-08-25 14:50
@CMJ111 what data stream type do you have? Are you sure you print the value that slider sends (in other words - where exactly do you check that slider send 0)? I just checked the code 0 can't be send if DS.min is 150. Server adjust the values to min/max. We'll try to reproduce of course. But quick look says that's not possible.

**Comment by CMJ111** [comment] 2021-08-25 14:58
Virtual Pin, Integer, no default value set and no exposure to automation.
Now the values sent are correct but I am not sure what changed it.  Before posting I did re-launch browser and mobile app with no change. 
 The only thing I did after my post was to edit one of the data streams and widget's max value for an unrelated reason.  Now when I test it all is well.  I double checked my serial monitor and it was definitely happening but like I said I cannot re-produce right now.

**Comment by doom369** [comment] 2021-08-25 15:01
@CMJ111 did you change the min/max values of the Data Stream after you created it?

**Comment by CMJ111** [comment] 2021-08-25 15:02
No not initially

**Comment by CMJ111** [comment] 2021-08-25 15:08
![image](https://user-images.githubusercontent.com/89530137/130815948-00a3cb6d-4abd-4433-a985-88e23bd1fb18.png)
![image](https://user-images.githubusercontent.com/89530137/130816224-41be9ac4-bf32-441d-8c4d-3c434ce41093.png)

**Comment by DmytroTool** [comment] 2021-08-25 17:02
@CMJ111 You have slider widget set for V16 pin DS and and settings you provided on the screen is V15

**Comment by CMJ111** [comment] 2021-08-25 19:12
![image](https://user-images.githubusercontent.com/89530137/130850834-e83727d4-bcee-40b3-8362-0cb573b53688.png)
Sent wrong SS, sorry about that.

**Comment by doom369** [comment] 2021-08-26 10:48
Ok. So closing for now. Fill free to reopen if you able to reproduce.

**Closed as completed by doom369** 2021-08-26 10:48 UTC
Labels: bug, web
