### ISSUE TITLE
ESP8266 provision failed (device hasn't connected to the cloud)

### ISSUE THREAD

**Issue by doom369** [blynkkk/beta#2] opened 2021-03-26 19:17 UTC
@vshymanskyy report from a user with failed provision:

```
ooking at serial monitor, in same time i use app, after i enter the correct local wifi id and password, i does this:
21:13:27.211 → [455413] Applying configuration…
21:13:27.211 → [455413] WiFi SSID: spiu Pass: parcului@@@@
21:13:27.211 → [455414] Blynk cloud: Zet_ICktYiasylehXYdO24aY2w1sjIRP @ blynk.cloud:443
21:13:27.211 → [455417] CONFIGURING => SWITCH_TO_STA
21:13:27.211 → [455419] Switching to STA…
21:13:27.304 → [455507] Hold the button to reset configuration…
21:13:27.304 → [455508] Hold the button to reset configuration…
21:13:27.304 →
21:13:27.304 → --------------- CUT HERE FOR EXCEPTION DECODER ---------------
21:13:27.352 →
21:13:27.352 → Exception (0):
21:13:27.352 → epc1=0x4020101c epc2=0x00000000 epc3=0x400043d5 excvaddr=0x00000000 depc=0x00000000
21:13:27.352 →
21:13:27.352 → >>>stack>>>
21:13:27.352 →
21:13:27.352 → ctx: cont
21:13:27.352 → sp: 3ffffbc0 end: 3fffffc0 offset: 0190
21:13:27.352 → 3ffffd50: ffffffff 00000000 3ffeff00 40100161
21:13:27.352 → 3ffffd60: 401004aa 00000000 00000000 40100534
21:13:27.352 → 3ffffd70: c0034004 0000005b 3fff2264 00000020
21:13:27.352 → 3ffffd80: 4020e040 3fff0178 3ffe8a49 00000022
21:13:27.352 → 3ffffd90: 3fffc200 40100470 3fffc258 4000050c
21:13:27.352 → 3ffffda0: 400043e6 00000030 00000016 ffffffff
21:13:27.352 → 3ffffdb0: 400044ab 3fffc718 3ffffea0 08000000
21:13:27.399 → 3ffffdc0: 60000200 08000000 00000000 00000000
21:13:27.399 → 3ffffdd0: 0000ffff 00042035 00002035 003fe000
21:13:27.399 → 3ffffde0: 40261b50 0000049c 003fe000 00000030
21:13:27.399 → 3ffffdf0: 00000000 3fff05e8 00000000 00000022
21:13:27.399 → 3ffffe00: 3fffc200 40100470 3fffc258 4000050c
21:13:27.399 → 3ffffe10: 4023ceec 00000030 00000016 ffffffff
21:13:27.399 → 3ffffe20: 4023cee9 00000001 3fff02a6 3fff02a6
21:13:27.399 → 3ffffe30: 3ffef540 3fff2920 00000000 000000df
21:13:27.399 → 3ffffe40: 00000008 00000000 ffffffff 3fff0fa4
21:13:27.399 → 3ffffe50: 00000001 00000000 3ffee60c 00000030
21:13:27.399 → 3ffffe60: 0000002e 0000007e 00000013 3ffee60c
21:13:27.445 → 3ffffe70: 000048d8 00000001 00000020 40100c37
21:13:27.445 → 3ffffe80: 00000000 4000444e 000007dd 3fff02b8
21:13:27.445 → 3ffffe90: 00000002 40105e67 00000001 60000200
21:13:27.445 → 3ffffea0: 00000002 4000410f 00001001 00000205
21:13:27.445 → 3ffffeb0: 3fffc718 40004a3c 000003fe 40261b50
21:13:27.445 → 3ffffec0: 3fffc718 401060f8 000003fe 40100570
21:13:27.445 → 3ffffed0: 40253f44 000003fe 3fff0bdc 40253f2d
21:13:27.445 → 3ffffee0: 3fff537c 40254017 3fff4edc 0000049c
21:13:27.445 → 3ffffef0: 000003fd 3fff02b8 3fff4edc 40253ffa
21:13:27.445 → 3fffff00: ffffff01 55aa55aa 0000002c 00000020
21:13:27.492 → 3fffff10: 00000020 000000f6 000000f5 aa55aa55
21:13:27.492 → 3fffff20: 000003ff 40253e1c 00000000 00000000
21:13:27.492 → 3fffff30: 3ffe8550 00000000 00000000 40253d93
21:13:27.492 → 3fffff40: 40105719 00000003 00000001 3fff4edc
21:13:27.492 → 3fffff50: 40253ea2 00000000 00000000 00000003
21:13:27.492 → 3fffff60: 40209309 3fff00e8 000003e8 402108b4
21:13:27.492 → 3fffff70: 3fffdad0 00000000 3fff00e8 40209718
21:13:27.492 → 3fffff80: 3fffdad0 00000000 3fff0278 4020212d
21:13:27.492 → 3fffff90: 3fffdad0 00000000 3fff0278 40207e85
21:13:27.492 → 3fffffa0: 3fffdad0 00000000 3fff0278 402109cc
21:13:27.538 → 3fffffb0: feefeffe feefeffe 3ffe8578 40100ef1
21:13:27.538 → <<<stack<<<
21:13:27.538 →
21:13:27.538 → --------------- CUT HERE FOR EXCEPTION DECODER ---------------
21:13:27.538 →
21:13:27.538 → ets Jan 8 2013,rst cause:2, boot mode:(3,6)
21:13:27.538 →
21:13:27.538 → load 0x4010f000, len 3584, room 16
21:13:27.538 → tail 0
21:13:27.538 → chksum 0xb0
21:13:27.538 → csum 0xb0
21:13:27.538 → v2843a5ac
21:13:27.538 → ~ld
21:13:27.960 → [388] Using default config.
21:13:27.960 → [388]
21:13:27.960 → ___ __ __
21:13:27.960 → / _ )/ /_ _____ / /__
21:13:27.960 → / _ / / // / _ / '/
21:13:27.960 → ///_, /////_
21:13:27.960 → /__/ v1.0.0-beta.1 on ESP8266
21:13:27.960 →
21:13:27.960 → [393] --------------------------
21:13:27.960 → [396] Product: SPIU
21:13:27.960 → [398] Hardware: 1.0.0
21:13:27.960 → [400] Firmware: 0.1.0 (build Mar 26 2021 20:55:26)
21:13:27.960 → [404] Device: ESP8266 @ 80MHz
21:13:27.960 → [407] MAC: A4:CF:12:F4:AA:5B
21:13:27.960 → [410] Flash: 4096K
21:13:27.960 → [412] ESP core: 2.7.4
21:13:27.960 → [414] ESP SDK: 2.2.2-dev(38a443e)
21:13:27.960 → [417] Boot Ver: 6
21:13:27.960 → [419] Boot Mode:1
21:13:27.960 → [420] FW info: 460768/1634304, MD5:f8f5e4b69ab702613f3e4d093e353976
21:13:28.195 → [623] Free mem: 31696
21:13:28.195 → [623] --------------------------
21:13:28.195 → [624] INIT => WAIT_CONFIG
21:13:28.195 → [660] Hold the button to reset configuration…
21:13:28.758 → [1222] AP SSID: Blynk SPIU-4E039
21:13:28.758 → [1222] AP IP: 192.168.4.1
21:13:28.758 → [1223] AP URL: blynk.setup
21:13:31.571 → [4037] Hold the button to reset configuration…
21:13:31.571 → [4038] Hold the button to reset configuration…
21:13:31.571 → [4039] Hold the button to reset configuration…
```

**Comment by doom369** [comment] 2021-03-26 19:36
> i use d1 mini, tried on two so far, same thing

**Comment by vshymanskyy** [comment] 2021-03-26 19:55
@thanxx did you try provisioning esp8266 devices on `blynk.cloud`?
I connected several devices for the demo without issues.

**Comment by spiutm** [comment] 2021-03-26 20:05
> @thanxx did you try provisioning esp8266 devices on `blynk.cloud`?
> I connected several devices for the demo without issues.

the serial monitor above appears after configuring wi-fi **checked**, reconnecting back to cloud **check** but it’s stuck on waiting for device online

**Comment by spiutm** [comment] 2021-03-27 07:24
I found the error,
// Uncomment your board, or configure a custom board in Settings.h
//#define USE_SPARKFUN_BLYNK_BOARD
#define USE_NODE_MCU_BOARD
//#define USE_WITTY_CLOUD_BOARD

it has to stay
//#define USE_NODE_MCU_BOARD
so don't touch that
now it is online on dashboard, ill try to connect whit the app also

**Comment by doom369** [comment] 2021-03-27 09:18
@spiutm thanks for the update. @vshymanskyy is that expected?

**Comment by spiutm** [comment] 2021-03-27 14:37
**update**, i flashed the second d1 mini i use, this time, whit the setting above, connected using the app whit no problems, as intended

**Comment by vshymanskyy** [comment] 2021-03-29 21:36
Closing in favor of #3

**Closed by vshymanskyy** 2021-03-29 21:36 UTC
Labels: bug, hardware
