### ISSUE TITLE
Bugs with Tabs widget

### ISSUE THREAD

**Issue by Smartnitz** [blynkkk/beta#50] opened 2021-04-11 07:54 UTC
Hey, 

I think I found a few issues with the Tabs Widget on android.

1. When creating new tabs in developer mode: After clicking on "Add Tab" and filling in the title, the tab appers to be created. But when I click on the "Back" Icon in the top left corner the new tab gets deleted. Sometimes using the "Back" button of my keyboard worked instead as a workaround

2. Its not possible to define the "Home Tab" - or the tab that gets opened first when I open a device. It also dosent seem to simply be the first tab in the menu, but the first tab that was created. I changed the order order of some tabs and after that it now always opens tab number 3 when opening a device

3. When using a swipe motion to cycle between tabs, the order seems to be messed up. For example swiping right from tab 1 to 2 works, but not from tab 2 to 3. Sometimes swiping right then dosent bring me back to the last tab. Sometimes it kinda jumpes over a certain tab when swiping  (maybe has somthing to do with me changing the order of tabs in developer mode?)

**Comment by Smartnitz** [comment] 2021-04-11 09:14
Also: I cant find an option to delete a certain tab without deleting all.

**Comment by alexkipar** [comment] 2021-04-12 11:08
@Smartnitz 

Are you using the latest available build, as there has been a bug with not saving widget settings when topbar's back button is tapped - it should be fixed already in the latest build.

About 'Home Tab': the app just caches the latest open tab in the device dashboard, so on the device reopen it should switch to the last tab selected in this device. If you will force close the app - app will open the very first tab.

In tabs settings, you should be able to delete the tab by swiping it. Also, you can change their order by drag.

Swipe cycle may be broken - I will check it

**Comment by Smartnitz** [comment] 2021-04-12 12:39
I am using build 1.0.12 which appears to be the current one in play store.

The behavior you descriped for the "home tab" dosent work for me. Right now it always opens tab number 3 first, which is the first tab i created. No matter which tab I selected last time in the device dashboard. Same happens if I close and restart the app.

But now I was able to delete a tab by swiping. Didnt know about that functionality. Thanks!

**Comment by alexkipar** [comment] 2021-04-13 11:15
@Smartnitz I've just uploaded a new build with fixes to tabs selection, swipe gesture and widget saving as well

**Comment by Smartnitz** [comment] 2021-04-13 12:59
Just tested it and most bugs are fixed. Thanks :)

One thing still happens for me though:

> When creating new tabs in developer mode: After clicking on "Add Tab" and filling in the title, the tab appers to be created. But when I click on the "Back" Icon in the top left corner the new tab gets deleted. Sometimes using the "Back" button of my keyboard worked instead as a workaround

Also, I noticed another thing:

Swiping between tabs dosent work, when do doing it on a Chart widget area with no data in it. I guess thats expected behavior to be able to scroll through the x axis of that chart, but I have a tab that consists out of a few Charts only, so swiping to other tabs from this one appeared impossible at first. Later I figured out that its possible when pointing my finger over the top tabs menu.

**Comment by alexkipar** [comment] 2021-04-13 13:15
@Smartnitz 
Swipe would not work on some widgets like graph, slider, etc. maybe I can enable that logic for Dev Mode, but definitely it would not be enabled everywhere.

> Later I figured out that its possible when pointing my finger over the top tabs menu.
You always can just click on the necessary tab to switch to it if swipe it not possible due to lots of full-width scrollable widgets

**Comment by alexkipar** [comment] 2021-04-13 13:23
@Smartnitz I can't reproduce the behavior with the back button click in the top left corner. Can you provide your smartphone model and android os version, as well do you enabled 'dont keep activities' in smartphone's developer options?

**Comment by Smartnitz** [comment] 2021-04-13 13:45
> Swipe would not work on some widgets like graph, slider, etc. maybe I can enable that logic for Dev Mode, but definitely it would not be enabled everywhere.

Yep, thats what I expected and I understand the reasons. But end users might not understand why they can swipe all tabs , but not on one tab when most of the screen is filled with charts. Is it maybe possible to allow swiping for certain areas of an unswipable widget? Like the area for the chart title ?

**Comment by Smartnitz** [comment] 2021-04-13 13:53
> @Smartnitz I can't reproduce the behavior with the back button click in the top left corner. Can you provide your smartphone model and android os version, as well do you enabled 'dont keep activities' in smartphone's developer options?

I did some more testing and figured out that the current behavior is like this:
When I create a new tab or delete an old tab and then go back (no matter if with the button on the top left or with keyboard button) its dosent work. I just get back to the tab menu but my changes are gone. Howerever it allways works, when I do this a second time (no matter if with the button on the top left or with keyboard button). So right now I always have to do the same process twice to apply the changes to the tabs.

Smartphone: Huawei P20 Pro
Anroid version: 10.0.0.182
Cant find the smartphone's developer options to check for 'dont keep activities', sorry :(

**Comment by doom369** [comment] 2021-04-21 17:08
looks like fixed to me.

**Closed by doom369** 2021-04-21 17:08 UTC
Labels: Android, bug, ready to test
